### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by echu18** [echu18/etsy_clone#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds
- [x] Demo user logs in
- [x] User cannot add to cart without logging in
- [x] Clicking outside of the login modal closes the modal

**Comment by ryan-mapa** [comment]
Great start! Bring back the weeb plzthnx
